# Use Node.js as the base (keep in sync with repo .nvmrc)
FROM node:22-alpine
ENV CHOKIDAR_USEPOLLING=true
ENV CHOKIDAR_INTERVAL=300
ENV HOST 0.0.0.0
ENV PORT=3030

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json to the container
COPY package.json ./
COPY package-lock.json* ./

# Install dependencies with retry mechanism and using npmjs registry explicitly
RUN npm config set registry https://registry.npmjs.org/ && \
    npm config set fetch-retry-maxtimeout 600000 && \
    npm config set fetch-retry-mintimeout 10000 && \
    npm config set fetch-retries 5 && \
    npm install || (sleep 5 && npm install) || (sleep 10 && npm install --no-package-lock)

#managed by volume mount in docker compose
#COPY . . 

EXPOSE 3030

CMD ["npm", "start"]

