services:
    goals_backend:
        container_name: goals_backend
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        restart: unless-stopped
        expose:
          - "5059"
        depends_on:
          - goals_db
        networks:
            - prod_network

    goals_db:
        container_name: goals_db
        build:
            context: ./db
            dockerfile: Dockerfile.prod
        volumes:
          - prod_goal_db:/data
          - ${BACKUP_PATH:-/var/lib/goals/backups}:/backups
        networks:
          - prod_network

    goals_frontend:
        container_name: goals_frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        expose:
          - "3030"
        restart: unless-stopped
        networks:
          - prod_network
        
    goals_router:
        container_name: goals_router
        build:
            context: ./router
            dockerfile: Dockerfile.prod
        expose:
          - "80"
        depends_on:
          - goals_backend
          - goals_frontend
        networks:
          - prod_network
        restart: unless-stopped

    goals_cloudflared:
        container_name: goals_cloudflared
        image: cloudflare/cloudflared:latest
        command: tunnel run --token ${GOALS_CLOUDFLARED_TOKEN}
        restart: unless-stopped
        networks:
          - prod_network

volumes:
    prod_goal_db:

networks:
    prod_network:
        driver: bridge
    
