services:
    goals_backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        restart: unless-stopped
        ports:
          - "5057:5057"
        volumes:
          - ./backend/:/usr/src/app
          - /usr/src/app/target
        networks:
            - dev_network
            #    db:
            #build:
            #context: ./db
            #dockerfile: Dockerfile.dev
            #ports:
            #- "5432:5432"
            #networks:
            #- dev_network
            #volumes:
            #- goal_db:/var/lib/postgresql/data
            #restart: unless-stopped
    goals_db:
      build:
          context: ./db
          dockerfile: Dockerfile.dev
      ports:
        - "7474:7474"
        - "7687:7687"
      volumes:
        - goal_db:/data
      networks:
        - dev_network

    goals_frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
          - ./frontend:/app
          - /app/node_modules
        environment:
          - CHOKIDAR_USEPOLLING=true #enable polling
        ports:
          - "3000:3000"
        restart: unless-stopped

    goals_cloudflared:
      image: cloudflare/cloudflared:latest
      command: tunnel run --token ${GOALS_CLOUDFLARED_TOKEN}
      restart: unless-stopped
      networks:
        - dev_network

volumes:
  goal_db:

networks:
  dev_network:
    driver: bridge
    
