name: Self-hosted Deploy

on:
  push:
    branches: [ prod ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build containers
        run: docker compose -p prod -f docker-compose.prod.yaml build

      - name: Deploy stack
        run: docker compose -p prod -f docker-compose.prod.yaml up -d
