name: Main Branch Checks

on:
  push:
    branches: [ main ]

jobs:
  quick-checks:
    name: Basic Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
      
      - name: Check backend formatting
        run: cargo fmt --manifest-path=backend/Cargo.toml --all -- --check
      
      - name: Check backend with clippy
        run: cargo clippy --manifest-path=backend/Cargo.toml -- -D warnings
        
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Check frontend with ESLint
        working-directory: ./frontend
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
      
      - name: Type check frontend
        working-directory: ./frontend
        run: npx tsc --noEmit 