name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changed-files:
    name: Detect Changed Files
    runs-on: self-hosted
    timeout-minutes: 5
    outputs:
      backend: ${{ steps.compute.outputs.backend }}
      frontend: ${{ steps.compute.outputs.frontend }}
      any_changes: ${{ steps.compute.outputs.any_changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Compute changed files
        id: compute
        shell: bash
        run: |
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          echo "Base: $BASE_SHA"
          echo "Head: $HEAD_SHA"
          git fetch --no-tags --depth=1 origin "+$BASE_SHA:$BASE_SHA" "+$HEAD_SHA:$HEAD_SHA" || true
          CHANGED_FILES=$(git diff --name-only "$BASE_SHA"..."$HEAD_SHA" || true)
          echo "Changed files:\n$CHANGED_FILES"
          backend_changed=false
          frontend_changed=false
          if echo "$CHANGED_FILES" | grep -q '^backend/'; then backend_changed=true; fi
          if echo "$CHANGED_FILES" | grep -q '^frontend/'; then frontend_changed=true; fi
          any_changes=false
          if [ "$backend_changed" = true ] || [ "$frontend_changed" = true ]; then any_changes=true; fi
          echo "backend=$backend_changed" >> "$GITHUB_OUTPUT"
          echo "frontend=$frontend_changed" >> "$GITHUB_OUTPUT"
          echo "any_changes=$any_changes" >> "$GITHUB_OUTPUT"

  check-previous-runs:
    name: Check Previous Test Runs
    runs-on: self-hosted
    permissions:
      contents: read
      actions: read
    timeout-minutes: 3
    outputs:
      backend_previously_failed: ${{ steps.check-failures.outputs.backend_failed }}
      frontend_previously_failed: ${{ steps.check-failures.outputs.frontend_failed }}
    steps:
      - name: Check for previous failures
        id: check-failures
        run: |
          # Initialize all outputs to false by default
          echo "backend_failed=false" >> $GITHUB_OUTPUT
          echo "frontend_failed=false" >> $GITHUB_OUTPUT

          # Get repository in owner/repo format
          REPO="${GITHUB_REPOSITORY}"

          # Try to get workflow runs with error handling
          echo "Checking previous runs for $REPO"

          # Check workflow conclusion (best-effort signal)
          workflow_status=$(gh api "/repos/${REPO}/actions/workflows/pr-checks.yml/runs" --jq '.workflow_runs[0].conclusion // "unknown"' 2>/dev/null || echo "unknown")
          echo "Previous workflow status: $workflow_status"
          if [ "$workflow_status" == "failure" ]; then
            echo "backend_failed=true" >> $GITHUB_OUTPUT
            echo "frontend_failed=true" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # BACKEND PIPELINE (lint, build, unit tests)
  backend-verify:
    name: Backend Lint, Build & Unit Tests
    needs: [changed-files, check-previous-runs]
    if: ${{ needs.changed-files.outputs.backend == 'true' || needs.check-previous-runs.outputs.backend_previously_failed == 'true' }}
    runs-on: self-hosted
    timeout-minutes: 45
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            backend/target
          key: cargo-${{ runner.os }}-${{ hashFiles('backend/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Lint with clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --verbose

      - name: Unit tests
        run: cargo test --lib

  # FRONTEND PIPELINE (lint, build, unit tests)
  frontend-verify:
    name: Frontend Lint, Build & Unit Tests
    needs: [changed-files, check-previous-runs]
    if: ${{ needs.changed-files.outputs.frontend == 'true' || needs.check-previous-runs.outputs.frontend_previously_failed == 'true' }}
    runs-on: self-hosted
    permissions:
      contents: read
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint with ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Type check with TypeScript
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test:ci

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: frontend-test-coverage
          path: frontend/coverage/
          retention-days: 30
      
  # DEPLOYMENT CHECK
  deploy-ready:
    name: Ready for Deployment
    needs: [backend-verify, frontend-verify]
    if: always()
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Evaluate overall workflow result
        run: |
          echo "backend-verify: ${{ needs.backend-verify.result }}"
          echo "frontend-verify: ${{ needs.frontend-verify.result }}"
          back_ok="${{ needs.backend-verify.result }}"
          front_ok="${{ needs.frontend-verify.result }}"
          if { [ "$back_ok" != "success" ] && [ "$back_ok" != "skipped" ]; } || \
             { [ "$front_ok" != "success" ] && [ "$front_ok" != "skipped" ]; }; then
            echo "One or more jobs failed. PR is not ready for deployment."
            exit 1
          else
            echo "All checks passed or were skipped appropriately! This PR is ready to be merged to prod for deployment."
          fi
